parameters:
#    cwb_core.example.class: Cwb\CoreBundle\Example

services:
#    cwb_core.example:
#        class: %cwb_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
